heat_template_version: 2014-10-16


description: Serveur avec une seule machine


parameters:

  image:
    type: string
    description: Image pour le serveur
    default: xenial-server-cloudimg-amd64-disk1
    constraints:
      - custom_constraint: glance.image
  
  flavor:
    type: string
    description: Gabarit pour le serveur
    default: 2048-10-1-1
    constraints:
      - custom_constraint: nova.flavor
  
  internal_network:
    type: string
    description: Sous-reseau interne
    default: switch1-nat
    constraints:
      - custom_constraint: neutron.network
  
  external_network:
    type: string
    description: Reseau externe
    default: 1fa7fade-2722-4677-9e2b-da22d385202b
  
  key:
    type: string
    description: Nom de la paire de cles
    default: key-team1
    constraints:
      - custom_constraint: nova.keypair
  
  
resources:

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: internal_network }
      key_name: { get_param: key }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install python-minimal -y
        wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
        python server.py
        
  floating_addr:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
  
  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_addr }
      port_id: { get_attr: [server, addresses, {get_param: internal_network}, 0, port] }